# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"OneLine": "00_boxprimitives.ipynb",
         "LineObj": "00_boxprimitives.ipynb",
         "plot_lines": "00_boxprimitives.ipynb"}

modules = ["lineprims.py",
           "gen.py"]

doc_url = "https://dangraf.github.io/box_generator/"

git_url = "https://github.com/dangraf/box_generator/tree/master/"

def custom_doc_links(name): return None
